export default [
  {
    "PermitId": 1,
    "PermitNo": "PTW-2025-001",
    "TaskName": "Replace HVAC System",
    "RequestedBy": "Bran Stark",
    "Status": "Request",
    "DateOfRequest": "2025-05-19",
    "Priority": "High",
    "Department": "Mechanical",
    "WorkLocation": "Plant 2, Rooftop, Zone B",
    "StartDate": "2025-01-20T08:00:00",
    "EndDate": "2025-05-21T18:00:00",
    "Equipment": "HVAC Unit",
    "Description": "Replacement of HVAC system. Risk of fire/explosion and toxic fumes.",
    "CurrentTab": "General Info",
    "Tag": "Request"
  },
  {
    "PermitId": 2,
    "PermitNo": "PTW-2025-002",
    "TaskName": "Electrical Panel Maintenance",
    "RequestedBy": "Arya Stark",
    "Status": "Procedure Completed",
    "DateOfRequest": "2025-05-20",
    "Priority": "High",
    "Department": "Electrical",
    "WorkLocation": "Electrical Room, Plant 1",
    "StartDate": "2025-01-22T09:00:00",
    "EndDate": "2025-02-22T17:00:00",
    "Equipment": "Electrical Panel",
    "Description": "Maintenance work involving risk of electric shock and arc flash.",
    "CurrentTab": "Closure",
    "Tag": "Procedure Completed"
  },
  {
    "PermitId": 3,
    "PermitNo": "PTW-2025-003",
    "TaskName": "Confined Space Cleaning",
    "RequestedBy": "Tyrion Lannister",
    "Status": "Approved",
    "DateOfRequest": "2025-05-21",
    "Priority": "High",
    "Department": "Safety",
    "WorkLocation": "Storage Tank 5, Plant 3",
    "StartDate": "2025-03-23T07:00:00",
    "EndDate": "2025-03-23T15:00:00",
    "Equipment": "Ventilation Unit",
    "Description": "Cleaning in confined space with risk of toxic gas and oxygen deficiency.",
    "CurrentTab": "Risk assessment",
    "Tag": "Approved"
  },
  {
    "PermitId": 4,
    "PermitNo": "PTW-2025-004",
    "TaskName": "Roof Repair",
    "RequestedBy": "Jon Snow",
    "Status": "Issued",
    "DateOfRequest": "2025-05-22",
    "Priority": "High",
    "Department": "Maintenance",
    "WorkLocation": "Roof, Plant 1",
    "StartDate": "2025-02-24T08:00:00",
    "EndDate": "2025-05-24T16:00:00",
    "Equipment": "Fall Arrest Kit",
    "Description": "Repair work at height with fall risk and dropped object hazard.",
    "CurrentTab": "Work & Contractor details",
    "Tag": "Issued"
  },
  {
    "PermitId": 5,
    "PermitNo": "PTW-2025-005",
    "TaskName": "Pipe Replacement",
    "RequestedBy": "Sansa Stark",
    "Status": "Suspended",
    "DateOfRequest": "2025-05-23",
    "Priority": "High",
    "Department": "Mechanical",
    "WorkLocation": "Chemical Plant, Zone C",
    "StartDate": "2025-03-25T07:00:00",
    "EndDate": "2025-05-26T17:00:00",
    "Equipment": "Pipe Cutter",
    "Description": "Replacement of pipes with fire and toxic fume hazards.",
    "CurrentTab": "More Details",
    "Tag": "Suspended"
  },
  {
    "PermitId": 6,
    "PermitNo": "PTW-2025-006",
    "TaskName": "Machine Installation",
    "RequestedBy": "Robb Stark",
    "Status": "Request",
    "DateOfRequest": "2025-05-24",
    "Priority": "Medium",
    "Department": "Operations",
    "WorkLocation": "Assembly Line 3",
    "StartDate": "2025-02-27T08:00:00",
    "EndDate": "2025-05-28T18:00:00",
    "Equipment": "Hoist",
    "Description": "Installation of new machinery with risk from heavy lifting.",
    "CurrentTab": "General Info",
    "Tag": "Request"
  },
  {
    "PermitId": 7,
    "PermitNo": "PTW-2025-007",
    "TaskName": "Fire Alarm System Maintenance",
    "RequestedBy": "Jorah Mormont",
    "Status": "Approved",
    "DateOfRequest": "2025-04-25",
    "Priority": "Medium",
    "Department": "Electrical",
    "WorkLocation": "Control Room",
    "StartDate": "2025-04-29T09:00:00",
    "EndDate": "2025-01-29T15:00:00",
    "Equipment": "Alarm Tester",
    "Description": "Fire alarm system check with potential for false alarms.",
    "CurrentTab": "Risk assessment",
    "Tag": "Approved"
  },
  {
    "PermitId": 8,
    "PermitNo": "PTW-2025-008",
    "TaskName": "Chemical Storage Tank Inspection",
    "RequestedBy": "Samwell Tarly",
    "Status": "Request",
    "DateOfRequest": "2025-01-26",
    "Priority": "High",
    "Department": "Safety",
    "WorkLocation": "Chemical Storage Area",
    "StartDate": "2025-02-30T07:00:00",
    "EndDate": "2025-05-30T16:00:00",
    "Equipment": "Gas Detector",
    "Description": "Inspection of chemical tank with gas hazard risk.",
    "CurrentTab": "General Info",
    "Tag": "Request"
  },
  {
    "PermitId": 9,
    "PermitNo": "PTW-2025-009",
    "TaskName": "Chemical Tank Scaffolding",
    "RequestedBy": "Theon Greyjoy",
    "Status": "Issued",
    "DateOfRequest": "2025-03-27",
    "Priority": "High",
    "Department": "Construction",
    "WorkLocation": "Building Exterior",
    "StartDate": "2025-02-31T08:00:00",
    "EndDate": "2025-03-31T17:00:00",
    "Equipment": "Scaffold",
    "Description": "Scaffolding setup at height with fall and object hazards.",
    "CurrentTab": "Work & Contractor details",
    "Tag": "Issued"
  },
  {
    "PermitId": 10,
    "PermitNo": "PTW-2025-010",
    "TaskName": "Boiler Maintenance",
    "RequestedBy": "Gendry Waters",
    "Status": "Request",
    "DateOfRequest": "2025-04-28",
    "Priority": "High",
    "Department": "Utilities",
    "WorkLocation": "Boiler Room, Plant 2",
    "StartDate": "2025-02-01T07:00:00",
    "EndDate": "2025-06-01T17:00:00",
    "Equipment": "Boiler",
    "Description": "Scheduled boiler maintenance. Details pending.",
    "CurrentTab": "General Info",
    "Tag": "Request"
  },
  {
    "PermitId": 11,
    "PermitNo": "PTW-2025-011",
    "TaskName": "Fuel Line Inspection",
    "RequestedBy": "Benjen Stark",
    "Status": "Approved",
    "DateOfRequest": "2025-03-28",
    "Priority": "High",
    "Department": "Safety",
    "WorkLocation": "Fuel Storage Area, Plant 3",
    "StartDate": "2025-01-02T08:00:00",
    "EndDate": "2025-06-02T16:00:00",
    "Equipment": "Leak Detector",
    "Description": "Inspection of fuel lines for leaks. Risk of fire and explosion.",
    "CurrentTab": "Risk assessment",
    "Tag": "Approved"
  },
  {
    "PermitId": 12,
    "PermitNo": "PTW-2025-012",
    "TaskName": "Cooling Tower Cleaning",
    "RequestedBy": "Edd Tollett",
    "Status": "Request",
    "DateOfRequest": "2025-02-29",
    "Priority": "Medium",
    "Department": "Maintenance",
    "WorkLocation": "Cooling Tower 2, Plant 1",
    "StartDate": "2025-04-03T07:00:00",
    "EndDate": "2025-06-03T15:30:00",
    "Equipment": "Water Jet Cleaner",
    "Description": "Cleaning of cooling tower basin and fan blades. Risk of slips and high-pressure injuries.",
    "CurrentTab": "General Info",
    "Tag": "Request"
  },
  {
    "PermitId": 13,
    "PermitNo": "PTW-2025-013",
    "TaskName": "Transformer Oil Replacement",
    "RequestedBy": "Brienne of Tarth",
    "Status": "Issued",
    "DateOfRequest": "2025-04-30",
    "Priority": "High",
    "Department": "Electrical",
    "WorkLocation": "Substation, Plant 2",
    "StartDate": "2025-03-04T09:00:00",
    "EndDate": "2025-06-04T17:00:00",
    "Equipment": "Transformer Unit",
    "Description": "Replacement of transformer oil. Risk of fire and electrical shock.",
    "CurrentTab": "Work & Contractor details",
    "Tag": "Issued"
  },
  {
    "PermitId": 14,
    "PermitNo": "PTW-2025-014",
    "TaskName": "Ammonia Line Inspection",
    "RequestedBy": "Davos Seaworth",
    "Status": "Suspended",
    "DateOfRequest": "2025-03-30",
    "Priority": "High",
    "Department": "Refrigeration",
    "WorkLocation": "Cold Storage Plant, Zone A",
    "StartDate": "2025-04-05T07:00:00",
    "EndDate": "2025-06-05T15:00:00",
    "Equipment": "Gas Detector",
    "Description": "Inspection of ammonia lines for leaks. Risk of toxic exposure and cold burns.",
    "CurrentTab": "More Details",
    "Tag": "Suspended"
  },
  {
    "PermitId": 15,
    "PermitNo": "PTW-2025-015",
    "TaskName": "Welding Job for Support Frame",
    "RequestedBy": "Grey Worm",
    "Status": "Procedure Completed",
    "DateOfRequest": "2025-04-31",
    "Priority": "Medium",
    "Department": "Fabrication",
    "WorkLocation": "Workshop Bay 4",
    "StartDate": "2025-01-06T08:00:00",
    "EndDate": "2025-06-06T14:00:00",
    "Equipment": "Welding Machine",
    "Description": "Welding of metal support structure. Risk of fire and eye injury.",
    "CurrentTab": "Closure",
    "Tag": "Procedure Completed"
  }
]
